// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "mongodb+srv://gupta04mohit_vedaAi:VedaAI@cluster0.gbv3rs5.mongodb.net/vedaai?appName=Cluster0",
  },
});
