import { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({});

export const saveJournalEntry = async (req: Request, res: Response): Promise<void> => {
  try {
    const { mood, energy, symptoms, note, aiAnalysis } = req.body;

    // Find or create a default user for testing since auth isn't fully hooked up
    let user = await prisma.user.findFirst({ where: { email: 'test@veda.ai' } });
    if (!user) {
      user = await prisma.user.create({
        data: {
          name: 'Test User',
          email: 'test@veda.ai',
          role: 'USER',
        }
      });
    }

    // Save the Wellness Log
    const log = await prisma.wellnessLog.create({
      data: {
        userId: user.id,
        date: new Date(),
        mood: mood,
        healthScore: Number(energy) * 10, // Convert 1-10 to 1-100
      }
    });

    // Save Symptoms if any
    if (symptoms && symptoms !== 'None' && symptoms.trim() !== '') {
      await prisma.symptom.create({
        data: {
          userId: user.id,
          symptomsList: symptoms,
          severity: 'Moderate',
          aiAnalysis: aiAnalysis || 'Analysis generated by Next.js backend'
        }
      });
    }

    res.status(201).json({ message: 'Journal entry saved to database', logId: log.id });
  } catch (error) {
    console.error("Database save error:", error);
    res.status(500).json({ message: 'Error saving journal entry to database' });
  }
};
